# Generated by Django 4.2.29 on 2026-04-04 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '测试项目',
                'verbose_name_plural': '测试项目',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='用例标题')),
                ('steps', models.JSONField(default=list, verbose_name='测试步骤')),
                ('variables', models.JSONField(default=dict, verbose_name='变量池')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '启用'), ('archived', '归档')], default='draft', max_length=20, verbose_name='状态')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, verbose_name='套件描述')),
                ('variables', models.JSONField(default=dict, verbose_name='套件变量')),
                ('ordered_case_ids', models.JSONField(default=list, verbose_name='用例顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='执行结果')),
                ('result_log', models.TextField(blank=True, verbose_name='执行日志')),
                ('elapsed_time', models.FloatField(default=0.0, verbose_name='耗时(s)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='api.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '用例执行记录',
                'verbose_name_plural': '用例执行记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(default=dict, verbose_name='执行汇总')),
                ('stop_on_failure', models.BooleanField(default=False, verbose_name='遇败即停')),
                ('results', models.JSONField(default=list, verbose_name='详细结果')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='api.testsuite', verbose_name='所属套件')),
            ],
            options={
                'verbose_name': '套件执行批次',
                'verbose_name_plural': '套件执行批次',
                'ordering': ['-created_at'],
            },
        ),
    ]
