# Generated by Django 4.2.29 on 2026-04-04 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrecord',
            name='screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/%Y/%m/%d/', verbose_name='失败截图'),
        ),
    ]
