# Generated by Django 4.2.29 on 2026-04-04 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_testrecord_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='标签'),
        ),
        migrations.CreateModel(
            name='EnvConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='环境名称')),
                ('base_url', models.URLField(blank=True, verbose_name='基础URL')),
                ('variables', models.JSONField(default=dict, help_text='如数据库连接、Token等', verbose_name='环境变量')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envs', to='api.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
            },
        ),
    ]
