# Generated by Django 4.2.29 on 2026-04-04 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_testcase_tags_envconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='envconfig',
            name='db_config',
            field=models.JSONField(blank=True, default=dict, help_text='{"host": "...", "port": 3306, "user": "...", "password": "...", "database": "..."}', verbose_name='数据库配置'),
        ),
        migrations.AddField(
            model_name='project',
            name='webhook_url',
            field=models.URLField(blank=True, help_text='如钉钉/企微群机器人', verbose_name='Webhook地址'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='setup_sql',
            field=models.TextField(blank=True, help_text='测试前执行的数据准备脚本', verbose_name='前置SQL'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='teardown_sql',
            field=models.TextField(blank=True, help_text='测试后执行的数据清理脚本', verbose_name='后置SQL'),
        ),
        migrations.AddField(
            model_name='testrecord',
            name='step_results',
            field=models.JSONField(blank=True, default=list, verbose_name='步骤详情'),
        ),
    ]
