# Generated by Django 4.2.29 on 2026-04-04 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_envconfig_db_config_project_webhook_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(verbose_name='并发用户数')),
                ('spawn_rate', models.IntegerField(verbose_name='每秒启动数')),
                ('duration', models.CharField(max_length=20, verbose_name='持续时长')),
                ('status', models.CharField(default='running', max_length=20, verbose_name='状态')),
                ('csv_prefix', models.CharField(blank=True, max_length=100, verbose_name='结果文件前缀')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='执行时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perf_records', to='api.testcase', verbose_name='所属用例')),
            ],
            options={
                'verbose_name': '性能测试记录',
                'verbose_name_plural': '性能测试记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
