# Generated by Django 4.2.29 on 2026-04-04 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_project_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('snapshot', models.JSONField(default=dict, verbose_name='快照')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.testcase', verbose_name='所属用例')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '用例版本',
                'verbose_name_plural': '用例版本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='testcaseversion',
            constraint=models.UniqueConstraint(fields=('case', 'version'), name='uniq_case_version'),
        ),
    ]

