# Generated by Django 4.2.29 on 2026-05-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_testrecord_attempts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envconfig',
            name='db_config',
            field=models.JSONField(blank=True, default=dict, help_text='数据库断言当前仅支持项目根下的 SQLite 文件（安全沙箱约束）。可用键：sqlite_path（相对路径，不可绝对路径或 ..），示例：{"sqlite_path": "db.sqlite3"}。', verbose_name='数据库配置'),
        ),
    ]
