# Generated by Django 4.2.29 on 2026-04-03 15:44

import apps.cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_testcase_steps_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='steps',
            field=models.JSONField(blank=True, default=apps.cases.models.default_test_steps, help_text='JSON 数组；每项建议含 type（ui|http）、method、url、selector、action 等，供 Selenium/Requests 执行引擎解析。', verbose_name='执行步骤'),
        ),
    ]
