# Generated by Django 4.2.29 on 2026-04-03 16:02

import apps.cases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_testcase_steps_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='variables',
            field=models.JSONField(blank=True, default=apps.cases.models.default_variables, help_text='键值对；步骤中可使用 {{key}} 占位符。执行时与 POST /run/ 传入的 variables 合并（请求体覆盖同名键）。', verbose_name='全局变量池'),
        ),
    ]
