# Generated by Django 4.2.29 on 2026-04-03 16:19

import apps.cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('cases', '0004_testcase_variables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='steps',
            field=models.JSONField(blank=True, default=apps.cases.models.default_test_steps, help_text='JSON 数组；type:http 走 requests，type:ui 走 Selenium（action: open/click/input/wait_visible/sleep 等），可与 HTTP 步骤混排。', verbose_name='执行步骤'),
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('variables', models.JSONField(blank=True, default=apps.cases.models.default_variables, help_text='执行套件时并入变量池（在用例 variables 之后、请求体 variables 之前覆盖）。', verbose_name='套件变量')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suites', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuiteCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_cases', to='cases.testsuite', verbose_name='套件')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_memberships', to='cases.testcase', verbose_name='用例')),
            ],
            options={
                'verbose_name': '套件用例',
                'verbose_name_plural': '套件用例',
                'ordering': ['order', 'id'],
            },
        ),
    ]
