# Generated by Django 4.2.29 on 2026-04-03 16:25

import apps.cases.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_testsuite_and_suitecase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiteRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stop_on_failure', models.BooleanField(default=False, verbose_name='遇败即停')),
                ('summary', models.JSONField(blank=True, default=apps.cases.models.default_suite_run_summary, help_text='如 {"total","passed","failed"}', verbose_name='汇总')),
                ('results', models.JSONField(blank=True, default=apps.cases.models.default_suite_run_results, help_text='每条含 case_id、case_title、record_id、status、elapsed_time', verbose_name='明细')),
                ('suite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suite_runs', to='cases.testsuite', verbose_name='套件')),
            ],
            options={
                'verbose_name': '套件执行记录',
                'verbose_name_plural': '套件执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
