# Generated by Django 4.2.29 on 2026-04-03 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0003_alter_testcase_steps_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', '执行中'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('result_log', models.TextField(blank=True, verbose_name='执行日志')),
                ('elapsed_time', models.FloatField(default=0, help_text='整次执行总耗时', verbose_name='耗时(秒)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='cases.testcase', verbose_name='测试用例')),
            ],
            options={
                'verbose_name': '执行记录',
                'verbose_name_plural': '执行记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
